# this is a docker-compose file for developement
# see deploy/docker-compose.yaml for a deployment template

services:
  fakturyfy:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    develop:
      watch:
        - action: rebuild
          path: ./
