FROM python:3.11
WORKDIR /app

COPY --from=manakjiri/fakturyfy:main /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY --from=manakjiri/fakturyfy:main /app backend

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY config.json backend/config.json
COPY launcher.py launcher/launcher.py

