# Generated by Django 5.0.2 on 2024-02-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("abbreviation", models.CharField(max_length=50, unique=True)),
                ("ic_number", models.IntegerField()),
                ("tax_number", models.CharField(blank=True, max_length=15)),
                ("tax_note", models.TextField(blank=True)),
                ("address", models.CharField(max_length=150)),
                ("zip_code", models.CharField(max_length=10)),
                ("city", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("bank_account", models.CharField(max_length=50)),
                ("bank_code", models.CharField(max_length=4)),
                ("bank_name", models.CharField(blank=True, max_length=50)),
                ("logo", models.ImageField(blank=True, upload_to="logos")),
            ],
        ),
    ]
