# Generated by Django 5.0.2 on 2024-02-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_entity_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='bank_code',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
