# Generated by Django 5.0.2 on 2024-02-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_entity_bank_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="ic_number",
            field=models.CharField(max_length=15),
        ),
    ]
